### PR TITLE
Feature/server client hint dpr

### PR DESCRIPTION
**Pull request by anton-karlovskiy**

### CODE REVIEW

**Comment by anton-karlovskiy** [comment]
Please review this as well. No conflicts. :)

**Comment by addyosmani** [comment]
@anton-karlovskiy I may be wrong, but I feel like I'm missing where the implementation for this example is. Could you check I'm misunderstanding this PR? :)

* First commit appears to be a customized version of CRA https://github.com/GoogleChromeLabs/adaptive-loading/pull/46/commits/b1005bec0432af130d882027651185121126bd18 (but other than `square box` not seeing the implementation). Was this the only part we needed?
* Second commit is removing files https://github.com/GoogleChromeLabs/adaptive-loading/pull/46/commits/e1114ecbd7eaf469a7d51580712addb68a9ef290
* Third is package.json updates https://github.com/GoogleChromeLabs/adaptive-loading/pull/46/commits/5fd4f046f7dcbcbf19137db8910e66446c919e72
* Fourth is removing functions https://github.com/GoogleChromeLabs/adaptive-loading/pull/46/commits/30211c0014a811dd09a7d763ca25ff650b897903

**Comment by anton-karlovskiy** [comment]
@addyosmani Actually the main implementation is node server.js file as image sources in index.html are fed with response from server.js.

**Comment by addyosmani** [comment]
Thanks for clearing that up!

**Comment by addyosmani** [comment]
After reviewing the initial implementation, this LGTM. We're likely going to do deeper reviews once we begin to build out more complex integrations of the adaptive loading signals and how we balance usage on the server with client hints vs. client-side signals.

**Pull request merged**
