### PR TITLE
Feature/enhanced twitter

### PR DESCRIPTION
**Pull request by anton-karlovskiy**
@addyosmani 

Please check the current status.
https://adaptive-loading.web.app/react-twitter-save-data-loading(hook)

It's almost done. Just UI fixing on mobile for video element is left for now.
FYI: As I reported earlier, the original react-tweet project code is not so clean and structured, it has taken some time to implement the video feature.

### CODE REVIEW

**Comment by anton-karlovskiy** [comment]
@addyosmani 

It's ready for review.

**Comment by addyosmani** [comment]
Thanks, Anton! Will review today. Did you see my comment from https://github.com/GoogleChromeLabs/adaptive-loading/issues/83#issuecomment-548678003?

**Comment by anton-karlovskiy** [comment]
> Thanks, Anton! Will review today. Did you see my comment from [#83 (comment)](https://github.com/GoogleChromeLabs/adaptive-loading/issues/83#issuecomment-548678003)?

Sure, let me handle it.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

It's ready.

**Pull request merged**
