### PR TITLE
Feature/microsite

### PR DESCRIPTION
**Pull request by anton-karlovskiy**
@addyosmani 

This PR is not ready to be merged yet.
Just the Microsite build configuration is left. Since you might want to see the codebase, this PR is created.

Microsite is completed, and up and running on https://adaptive-loading.web.app/.

### CODE REVIEW

**Comment by anton-karlovskiy** [comment]
This PR is ready for review.

Microsite build configuration is set.
cna-memory-considerate-animation is deployed to https://adaptive-loading.web.app/cna-memory-considerate-animation which was up and running on some limited Firebase account.
cna-memory-considerate-animation build configuration is set.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Node apps are updated for serving static assets.

**Comment by addyosmani** [comment]
@anton-karlovskiy could you rebase this PR against master now that we've landed the updates to demos?

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Let me handle this and update you shortly.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

For cna-memory-considerate-animation project, build version was not working, although dev version working.
The cause was because we imported css from react-toggle package.

I tried all workarounds but did not help. So I just wrote the css in the component and it's fixed.
https://github.com/zeit/next-plugins/issues/266
https://github.com/zeit/next-plugins/issues/267

Please review and merge it.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

Thank you for your quick merge. I appreciate it.

**Pull request merged**
