### PR TITLE
Feature/next tv app

### PR DESCRIPTION
**Pull request by anton-karlovskiy**
@addyosmani 

Every thing is ready but for deployment to Adaptive Loading Firebase project.

If we have some idea of favicon and manifest, we can easily implement it as we have the head component structure already. Just assets are missing.

### CODE REVIEW

**Comment by anton-karlovskiy** [comment]
@addyosmani 

- It's deployed on https://adaptive-loading.web.app/next-show-adaptive-loading.
- CNA version is updated to the latest for microsite, cna-memory-considerate-animation and firebase functions.
- cna-memory-considerate-animation is updated with memory hook from react-adaptive-hooks package and Client Hint as initial value. The local copy of memory hook was removed.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

I think I should update app README, adaptive loading demos README, react-adaptive-hooks README and Microsite too.
I think it will be the end of this this project.

**Comment by addyosmani** [comment]
Great work on progress for this rewrite, Anton! Tested the latest deploys. I only have a few nits remaining that we have not shared on Slack so far:

* Navigation: Could we update nav to include a separator between Home and Back? (e.g `|`)
* Cross-browser testing: In Firefox, when manual testing has been checked and we turn on Poor Network/Memory, the view does not update to use the lower resolution resources. The preference is respected when you start navigating again through results, but it is not immediately there. This could be because Firefox doesn't support Client Hints nor some of the APIs on the client for doing detection, but we might want to just check if this is a bug with the  demo or the hooks.
* Routing: navigations result in `https://adaptive-loading.web.app/?page=3` or `https://adaptive-loading.web.app/show?id=80752`, which while render the correct response when navigating, don't if you go to these URLs. We know this is a Next.js nested routing issue but just noting for the future.
* Debugging: could we add a small area at the end of the page that includes: `Direct link to force slow mode`, `Direct link to force normal mode`.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
> Cross-browser testing

We had no bug with the implementation for adaptive loading like react-adaptive-hooks usage.
According to https://caniuse.com/#search=effectiveType and https://caniuse.com/#search=client%20hint, Firefox does not support `Client Hint` as well as `NetworkInformation.effectiveType` but we set the default values as initial values in the network and memory hook.

```
const ADAPTIVE_FACTORS = {
  ECT_LIMIT: '4g',
  DEVICE_MEMORY_LIMIT: 4,
  DEFAULT_ECT: '4g',
  DEFAULT_DEVICE_MEMORY: 8
};
```

```
const { effectiveConnectionType } = useNetworkStatus(clientHintEct || ADAPTIVE_FACTORS.DEFAULT_ECT);  
const { deviceMemory } = useMemoryStatus({deviceMemory: clientHintDeviceMemory || ADAPTIVE_FACTORS.DEFAULT_DEVICE_MEMORY});
```

So the returning values from network and memory hook are `4g(ADAPTIVE_FACTORS.DEFAULT_ECT)` and `8(ADAPTIVE_FACTORS.DEFAULT_DEVICE_MEMORY)`.
firefox

**Comment by anton-karlovskiy** [comment]
@addyosmani 
> Navigation

It's updated.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
> Debugging

I'd like to confirm first.
For `Direct link to force slow mode`, `Direct link to force normal mode` I think we can produce the same effect with the debugging toggle and check box at the top of the app.

Then should we remove the current debugging option of toggle and checkbox or just add two links at the bottom with the previous option?

**Comment by anton-karlovskiy** [comment]
@addyosmani 

https://adaptive-loading.web.app/demos
- Microsite is updated.
- App README is updated.
- Repo README is updated.

**Comment by addyosmani** [comment]
Nice work on the latest updates, Anton. Can confirm Firefox is now working as expected 👍 

"For Direct link to force slow mode, Direct link to force normal mode I think we can produce the same effect with the debugging toggle and check box at the top of the app." The purpose of the links is for people (e.g web performance experts) that might want to run a before/after on the app but won't be able to get a direct link to do this using the toggle and check box. An alternative to having links in the footer is that we could just have these links in the README and that would achieve the same. I'd be cool with that.

**Comment by addyosmani** [comment]
Could we update https://github.com/GoogleChromeLabs/adaptive-loading/tree/72baaaf7ef7918ce557b7776398f623ada8b2b0f/next-show-adaptive-loading with two links to the query-parameter versions to force slow/normal modes?

**Comment by anton-karlovskiy** [comment]
@addyosmani 

It's updated with two links to the query-parameter in Glitch project as well as this GitHub project.
https://anton-karlovskiy-next-show-adaptive-loading.glitch.me/
https://adaptive-loading.web.app/next-show-adaptive-loading

**Comment by anton-karlovskiy** [comment]
@addyosmani 

I tested it on Glitch and Firebase. Glitch version is working well with debugging links. But I'm afraid the links throw errors when we click on them probably due to Next.js nested route issue.
Manually putting the query parameter in the address bar for debugging is working well on Firebase as well.

**Comment by anton-karlovskiy** [comment]
@addyosmani 

It's fixed on Firebase too. So we can use debugging links on either hosting server.

**Comment by addyosmani** [comment]
Thanks, Anton. This looks good enough to land now!

For later, here's the before/after WebPageTest trace over 4G: https://www.webpagetest.org/video/compare.php?tests=191220_YV_f523eb63831516f1b2c3c36086034cfc,191220_Z3_90649a7fe05971268a38885c78b3250b

**Pull request merged**
