### PR TITLE
add mediaCapabilities hook

### PR DESCRIPTION
**Pull request by wingleung**
A proposal hook for #59 to see if there's any interest at this stage of the project.

### CODE REVIEW

**Comment by wingleung** [comment]
@googlebot I signed it!

**Comment by addyosmani** [comment]
Oh, nice. I have not heavily used https://developer.mozilla.org/en-US/docs/Web/API/Media_Capabilities_API before but this looks like it could be an interesting consideration for a fit. I'll read up on the API and circle back here.

**Comment by addyosmani** [comment]
@wingleung would you be interested in moving the discussion of adding Media Capabilities API support over to https://github.com/GoogleChromeLabs/react-adaptive-hooks now that the hooks portion of the project lives over there?

**Comment by wingleung** [comment]
> @wingleung would you be interested in moving the discussion of adding Media Capabilities API support over to [GoogleChromeLabs/react-adaptive-hooks](https://github.com/GoogleChromeLabs/react-adaptive-hooks) now that the hooks portion of the project lives over there?

done

**Pull request closed without merging**
