### PR TITLE
Feature/server client hint ect

### PR DESCRIPTION
**Pull request by anton-karlovskiy**

### CODE REVIEW

**Comment by addyosmani** [comment]
@anton-karlovskiy Could you resolve the conflicts this has against master? I believe this can be done from the web interface or just locally. The conflicts are against:

build.sh
clean.sh
functions/index.js
package.json

**Comment by anton-karlovskiy** [comment]
> @anton-karlovskiy Could you resolve the conflicts this has against master? I believe this can be done from the web interface or just locally. The conflicts are against:
> 
> build.sh
> clean.sh
> functions/index.js
> package.json

Yes, it's expected. :)

**Comment by anton-karlovskiy** [comment]
@addyosmani 
One by one merge, I'll resolve conflicts.

**Comment by addyosmani** [comment]
@anton-karlovskiy It looks like we may need one more brief round of conflict resolution on this one :)

**Comment by anton-karlovskiy** [comment]
Here conflicts. I'll resolve them and let you know. Thank you for your review.

**Comment by anton-karlovskiy** [comment]
@addyosmani Could you please review and merge the PR?

**Comment by anton-karlovskiy** [comment]
@addyosmani Here I think we should use local assets instead of glitch CDN images for more secure maintenance. I'll update and test the project and let you know so you can proceed with review and merge.
Thank you.

**Pull request merged**
