### PR TITLE
Feature/dixie

### PR DESCRIPTION
**Pull request by anton-karlovskiy**
@addyosmani 
It's ready for review.
Please have a look at the project README and give me some feedback.
There are minor faults like showing white screen on model-viewer loading.

### CODE REVIEW

**Comment by addyosmani** [comment]
This is a great start! Some feedback on the user-experience:

* I wonder if for `model-viewer`, we should experiment with preloading the poster and displaying it or a placeholder until the 3D model has finished loading: https://googlewebcomponents.github.io/model-viewer/examples/lazy-loading.html
* Wonder how far we can get with styling the background for `model-viewer`. e.g Looking at https://googlewebcomponents.github.io/model-viewer/ it appears to support a `background-color` attribute. Perhaps `rgb(43, 43, 43)`?
* Can we change `ThreeBox` as a label to `<model-viewer>` so text is `<model-viewer> On/Off`

**Comment by anton-karlovskiy** [comment]
@addyosmani 
OK, according to your feedback, let me update the PR.

**Comment by addyosmani** [comment]
> OK, according to your feedback, let me update the PR.

Happy to land once the changes are incorporated :)

**Comment by anton-karlovskiy** [comment]
Sure, sorry for being late.

**Comment by anton-karlovskiy** [comment]
@addyosmani 
2. background-color is set currently as #2b2b2b. The same as rgb(43, 43, 43).

**Comment by anton-karlovskiy** [comment]
@addyosmani 

For 2nd issue, we have the same memory overloaded entry and `GigaByte` in the following projects. I've updated `GigaByte` to `GB`. Shall we also remove the memory overloaded entry in those projects?

https://cna-memory-animation.firebaseapp.com/
https://adaptive-loading.web.app/cra-memory-considerate-loading-sketchfab/
https://adaptive-loading.web.app/cra-memory-considerate-loading/

**Comment by anton-karlovskiy** [comment]
@addyosmani 

You can check the current status of the project [here](https://adaptive-loading.web.app/react-dixie-memory-considerate-loading/).
I also reduced the height of the model to help it look compact. Please review it.

**Pull request merged**
